server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,image/svg+xml
    min-response-size: 1024

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}

app:
  cookie:
    secure: true
